### ISSUE TITLE
Replace libp2p with Wrapper over TCP

### ISSUE THREAD

**Issue by jordanschalm** [ubclaunchpad/cumulus#49]
`libp2p` doesn't really do anything for us and has been causing some problems.

We have a solid message layer that reads and writes messages from an `io.Writer`/`io.Reader`.

We need a wrapper around TCP for:
- Creating connections to other peers
- Expose a `net.Conn`

We need a model for "the other people on the network" that:
- [ ] Contains that peer's connection
- [ ] Has a reader on the stream that dispatches message to handlers
- [ ] Exposes a thread-safe `Write` method

We need:
- [ ] To keep track of the set of peers we're connected to
